SPM Support
appmetrica/protobuf-c pull request #1
Opened 2023-09-05 14:32 UTC by Sergey70

contrib

2023-09-05 15:46 UTC, GLinnik21 requested changes

2023-09-05 15:46 UTC, GLinnik21 commented on Package.swift
> +                    "-Wno-conversion"
SPM would not allow this flag with release version

2023-09-05 16:03 UTC, Sergey70 commented on Package.swift
> +                    "-Wno-conversion"
Any suggestion?

2023-09-05 18:06 UTC, Sergey70 commented on Package.swift
> +                    "-Wno-conversion"
Убрал флаг. Проверил в семпле, варнинги, вроде бы, не экспоузятся в сборку самого приложения. Предлагаю позже перепроверить это еще раз.

2023-09-06 10:55 UTC, GLinnik21 requested changes

2023-09-06 10:55 UTC, GLinnik21 commented on Package.swift
> +// swift-tools-version: 5.6
Maybe we can downgrade the version of the tools for better compatibility

2023-09-06 10:55 UTC, GLinnik21 commented on Package.swift
> +            path: "protobuf-c",
I would also add `sources:` param here as well, as protobuf-c build toolchain generates some files that could break SPM build.

2023-09-06 10:55 UTC, GLinnik21 commented on protobuf-c.podspec
> +  spec.tvos.deployment_target    = '10.0'
Why does iOS support start at 9.0 and tvOS at 10.0?
protobuf-c also supports macOS and watchOS.

2023-09-07 08:28 UTC, closed without merging